import type { Metadata } from "next";
import type { PropsWithChildren, FC } from 'react';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Inter } from "next/font/google";
import '@/styles/global.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: FC<PropsWithChildren> = (props) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          {props.children}
        </AntdRegistry>
      </body>
    </html>
  );
}

export default RootLayout;